### PR TITLE
Slim :shortcut string values are deprecated

### PR DESCRIPTION
**Pull request by ognevsky**
We have this error message almost everywhere:

```
Slim :shortcut string values are deprecated, use hash like { '#' => { :tag => 'div', :attr => 'id' } }
```

WARNING! 
This pull request crashes tests because of Skim gem (which is a development dependency): it requires Slim 1.2.2, but there was no such feature in such old version. Here is an issue about this https://github.com/jfirebaugh/skim/issues/23, so skim is not going to support newer versions of Slim.

### CODE REVIEW

**Comment by kossnocorp** [comment]
It won't be merged until https://github.com/jfirebaugh/skim/issues/23 is open.

**Comment by razum2um** [comment]
bump
jfirebaugh/skim#23 is closed now.

**Comment by kossnocorp** [comment]
@razum2um @yury thanks!

@ognevsky can you properly setup gemspec and make sure all tests are pass? Thanks!

**Comment by ognevsky** [comment]
@kossnocorp sure, I'll do it tomorrow.

**Comment by kossnocorp** [comment]
Thanks!

**Comment by razum2um** [comment]
@ognevsky @kossnocorp 
i did it in #6

**Comment by ognevsky** [comment]
@razum2um awesome, I'll close this one.

**Pull request closed without merging**
