### PR TITLE
Haml support through hack

### PR DESCRIPTION
**Pull request by gazay**
Btw, guys started working hard on Haml last days after 4 months break, so maybe soon we can do it easily.

### CODE REVIEW

**Comment by rwz** [comment]
Ok, this is waay too hacky for my taste. And it will definitely break right after haml guys decide to change something in these methods you override.

There is an idea to implement and propose a set of changes to Haml itself, making it more configurable, so we can add role support through native config API, much like we did with Slim.

**Comment by gazay** [comment]
Well, then you can wait from week till year. Do you remember when was released last stable version of haml? (3.1.4) - in november. They finish development of 3.1.5 now, but there nothing then removing sass and some small changes. For changing architecture for adding new separators dynamically they need to rewrite whole parser.
I don't really like that they did break for a half of year and didn't merged pull requests, so now I don't want to rewrite haml parser - I just did this pull because @kossnocorp asked about.

P.s. If you know better way to do this thing then rewrite haml parser - I'll glad to listen "not too hacky way" to do it and discuss.
P.p.s. If you don't want to forget about this gem after a week for several months and will support it and develop - you will not have problems with dependencies. When haml guys changed something - someone write issue about this here - something not working - you look into haml sources and fix it. It's better way I think then forgot about most popular template engine

**Comment by rwz** [comment]
I'll try to refactor Haml parser this weekend or more likely the next one. Will see how and if it will work out.

**Comment by gazay** [comment]
I think the best variant will be next: 
1. accepting this hack
2. rewriting Haml::Parser for accepting dynamic attributes
3. realizing in role check haml version for using hack for old versions and new native function for adding attributes for new haml version.

In this case role will support all versions and as result - more people can use role with haml.

**Comment by gazay** [comment]
And btw methods which I override - they weren't changed from 2010. So all versions from 2010 will support this hack

**Comment by kossnocorp** [comment]
I think we should create experimental version, something like role-rails 1.3.0.beta and use @gazay's Haml hack.

**Comment by gazay** [comment]
We decided with @kossnocorp that I'll do new version of role-rails with this commit as role-haml as fork of this repo, so I close this pull. Thanks guys

**Pull request closed without merging**
